baseurl = "http://example.com"
languagecode = "en-us"
pluralizelisttitles = false
title = "Adventure Time!"
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1
[params]
banner = "/uploads/2017/10/28/dollars.png"
description = "This is the Blog Page of altMavericks"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
